export const translations = {
    de: {
        nav_vision: "Vision", nav_product: "Produkt", nav_tech: "Technologie", nav_market: "Markt", nav_contact: "Kontakt",
        hero_title: "HAVENIS AI – <span class=\"highlight\">The Human Sensing Revolution</span>",
        hero_subtitle: "KI-gestütztes Vitalmonitoring durch unsichtbare Wellen – gesund, privat, präzise.",
        hero_cta_primary: "Seed-Investition prüfen", hero_cta_secondary: "Technologie entdecken",
        vision_title: "Vision & Mission",
        vision_text_1: "Wir revolutionieren Gesundheitsüberwachung und Sicherheit durch ethische KI-Sensorik. Unsere Vision ist eine Welt, in der Technologie schützt, ohne zu beobachten.",
        vision_text_2: "Unsere Mission: Die Entwicklung des weltweit führenden nicht-invasiven Sensing-Systems, das Privatsphäre respektiert und präventive Einblicke in Gesundheit und Sicherheit ermöglicht.",
        vision_promise: "Marktversprechen: „Sicherheit, die niemand sieht – Gesundheit, die alles bemerkt.“",
        vision_vis: 'Diagramm: "From Wi-Fi to Vital Sensing – The Next Interface of Health"',
        product_title: "Produktarchitektur: SENSING CORE V1.0",
        product_subtitle: "Eine robuste, skalierbare Plattform für nicht-invasive Wahrnehmung.",
        product_schema_title: "3D-Schema: Datenfluss",
        product_schema_text: "Unser System erfasst Wi-Fi CSI-Daten, verarbeitet sie lokal auf dem Edge AI Chip (SENSING CORE), extrahiert anonymisierte Metriken und sendet diese sicher an die Cloud für Analysen und Dashboards.",
        product_schema_vis: "3D-Schema: Sensing Core V1.0 (Erfassung → Edge AI → Cloud → Dashboard)",
        product_layers_title: "KI-Layer-Diagramm",
        product_layers_text: "Unsere KI basiert auf mehreren Ebenen: Signal-Vorverarbeitung, Feature-Extraktion mittels Deep Learning und Klassifikation von Haltungen, Bewegungen und Vitalparametern.",
        product_layers_vis: "KI-generiertes Layer-Diagramm",
        use_cases_title: "Use Cases: Wo HAVENIS AI transformiert",
        use_cases_subtitle: "Fokus auf Märkte mit höchstem Bedarf an Privatsphäre und Präzision.",
        use_case1_title: "Luxury Living & HNWI Security",
        use_case1_text: "Unsichtbare Einbruchserkennung, Sturzprävention in Privatresidenzen, diskrete Überwachung sensibler Bereiche ohne Kameras.",
        use_case1_vis: "Vis: Luxusinterieur mit unsichtbarem Schutzfeld",
        use_case2_title: "Healthcare & Assisted Living",
        use_case2_text: "Kontaktloses Monitoring von Vitaldaten (Atmung, HF), Sturzerkennung für Senioren, Analyse von SchlaMustern, Patientenüberwachung in Kliniken.",
        use_case2_vis: "Vis: Ärzte-Dashboard / Sleep Analytics",
        use_case3_title: "Smart Home Security",
        use_case3_text: "Präsenzerkennung zur intelligenten Steuerung von Licht/Klima, Einbruchsalarm ohne Fehlalarme durch Haustiere, DSGVO-konforme Überwachung.",
        use_case3_vis: "Vis: Smart Home Interface mit Präsenzanzeige",
        market_growth_title: "Markt & Wachstumspotenzial",
        market_growth_subtitle: "Wir adressieren den schnell wachsenden Markt für ethische Sensorik und Ambient Health.",
        market_chart_title: "HealthTech Market Growth (Global + EU)",
        market_chart_desc: "Der Markt für digitale Gesundheitslösungen wächst exponentiell, getrieben durch Demografie und Technologie.",
        market_chart_vis: "Chart: HealthTech Market Growth 2024–2030",
        market_comparison_title: "HAVENIS AI vs. Kamera-Systeme",
        market_comparison_desc: "Unser Alleinstellungsmerkmal ist die Kombination aus Präzision und absoluter Privatsphäre.",
        market_comparison_vis: "Vergleichsgrafik: HAVENIS vs. Kamera (Privacy, Accuracy, Adoption Rate)",
        market_exit_title_detail: "Strategischer Exit zu Big Tech",
        market_exit_text_detail: "Unser Fokus auf HNWIs und patentierte, ethische Technologie macht uns zum idealen Übernahmeziel für Google, Apple oder Amazon, die dringend eine datenschutzkonforme Lösung für ihre Ambient-Health-Ökosysteme benötigen.",
        financials_title: "Finanzbedarf & Wachstumsplan",
        financials_subtitle: "Wir suchen € 800.000 Seed-Kapital für Technologie-Finalisierung und Markteintritt.",
        financials_plan_title: "Kapitalplan (Seed → Series A)",
        financials_t1_date: "Jetzt (Seed)",
        financials_t1_amount: "€ 0,8 Mio.",
        financials_t1_use: "Finalisierung SENSING CORE V1.0, 10+ Pilotprojekte (HNWI/Kliniken), Aufbau Partnernetzwerk.",
        financials_t2_date: "Q3 2026 (Series A)",
        financials_t2_amount: "€ 2,5 - 3 Mio.",
        financials_t2_use: "Hardware-Miniaturisierung (Chip-Level), CE-Zertifizierung (MedTech), Skalierung Vertrieb DACH.",
        financials_alloc_title: "Investitionsallokation (Seed)",
        financials_cta_title: "Join the First 100 Seed Investors",
        financials_cta_desc: "Sichern Sie sich exklusiven Zugang und potenzielle IP Share Rights als früher Unterstützer. Jedes Ticket: € 10.000.",
        financials_cta_button: "Jetzt Seed-Investor werden",
        team_detail_title: "Team & Advisory Board",
        team_detail_subtitle: "Ein Kernteam mit Deep-Tech-Fokus, ergänzt durch Branchenexperten.",
        team_m1_name_detail: "Danilo Kuss",
        team_m1_role_detail: "CEO & CTO",
        team_m1_desc_detail: "Experte RF-KI & Embedded Systems.",
        team_m2_name_detail: "Sarah Le Roux",
        team_m2_role_detail: "COO & Strategie",
        team_m2_desc_detail: "B2B-Sales & Partnernetzwerke.",
        team_m3_name_detail: "Advisory Board",
        team_m3_role_detail: "(Geplant)",
        team_m3_desc_detail: "RegTech, MedTech & HNWI-Security.",
        team_map_vis: "Diagramm: Core Expertise Map (Forschung / AI / Sensing / Design / Business)",
        contact_form_title: "Kontakt & Pitchdeck-Anfrage",
        contact_form_subtitle: "Fordern Sie das vollständige Seed Investment Pitchdeck an. Nach Prüfung senden wir Ihnen das PDF automatisch zu.",
        contact_name: "Name",
        contact_email: "E-Mail",
        contact_type: "Investor-Typ",
        contact_select: "Bitte wählen...",
        contact_vc: "Venture Capital",
        contact_angel: "Business Angel",
        contact_fo: "Family Office",
        contact_strategic: "Strategischer Investor",
        contact_other: "Andere",
        contact_message: "Nachricht (Optional)",
        contact_button: "Pitchdeck / Investor PDF anfordern",
        contact_disclaimer: "Ihre Daten werden vertraulich behandelt und ausschließlich zur Übersendung des Pitchdecks und zur Kontaktaufnahme verwendet.",
        footer_copy_detail: "&copy; 2025 HAVENIS AI | Fürstenwalde, Deutschland | Alle Rechte vorbehalten.",
        footer_contact_detail: "info@havenis.ai",
        footer_version_detail: "Version Seed 1.0",
        cta_sending: "Sende Anfrage...",
        cta_success: "Erfolg! Pitchdeck wurde an Ihre E-Mail gesendet.",
        cta_error: "Fehler beim Senden. Bitte versuchen Sie es erneut.",
    },
    en: {
        nav_vision: "Vision", nav_product: "Product", nav_tech: "Technology", nav_market: "Market", nav_contact: "Contact",
        hero_title: "HAVENIS AI – <span class=\"highlight\">The Human Sensing Revolution</span>",
        hero_subtitle: "AI-powered vital monitoring through invisible waves – healthy, private, precise.",
        hero_cta_primary: "Explore Seed Investment", hero_cta_secondary: "Discover Technology",
        vision_title: "Vision & Mission",
        vision_text_1: "We are revolutionizing health monitoring and security through ethical AI sensing. Our vision is a world where technology protects without watching.",
        vision_text_2: "Our Mission: To develop the world's leading non-invasive sensing system that respects privacy and provides preventive insights into health and safety.",
        vision_promise: "Market Promise: “Security no one sees – Health that notices everything.”",
        vision_vis: 'Diagram: "From Wi-Fi to Vital Sensing – The Next Interface of Health"',
        product_title: "Product Architecture: SENSING CORE V1.0",
        product_subtitle: "A robust, scalable platform for non-invasive perception.",
        product_schema_title: "3D Schema: Data Flow",
        product_schema_text: "Our system captures Wi-Fi CSI data, processes it locally on the Edge AI chip (SENSING CORE), extracts anonymized metrics, and securely sends them to the cloud for analysis and dashboards.",
        product_schema_vis: "3D Schema: Sensing Core V1.0 (Capture → Edge AI → Cloud → Dashboard)",
        product_layers_title: "AI Layer Diagram",
        product_layers_text: "Our AI is based on multiple layers: signal preprocessing, feature extraction using deep learning, and classification of postures, movements, and vital parameters.",
        product_layers_vis: "AI-generated Layer Diagram",
        use_cases_title: "Use Cases: Where HAVENIS AI Transforms",
        use_cases_subtitle: "Focusing on markets with the highest demand for privacy and precision.",
        use_case1_title: "Luxury Living & HNWI Security",
        use_case1_text: "Invisible intrusion detection, fall prevention in private residences, discreet monitoring of sensitive areas without cameras.",
        use_case1_vis: "Vis: Luxury interior with invisible protection field",
        use_case2_title: "Healthcare & Assisted Living",
        use_case2_text: "Contactless monitoring of vitals (respiration, HR), fall detection for seniors, sleep pattern analysis, patient monitoring in clinics.",
        use_case2_vis: "Vis: Doctor's Dashboard / Sleep Analytics",
        use_case3_title: "Smart Home Security",
        use_case3_text: "Presence detection for intelligent control of lights/climate, intrusion alarm without false alarms from pets, GDPR-compliant monitoring.",
        use_case3_vis: "Vis: Smart Home Interface with presence display",
        market_growth_title: "Market & Growth Potential",
        market_growth_subtitle: "Addressing the rapidly growing market for ethical sensing and ambient health.",
        market_chart_title: "HealthTech Market Growth (Global + EU)",
        market_chart_desc: "The market for digital health solutions is growing exponentially, driven by demographics and technology.",
        market_chart_vis: "Chart: HealthTech Market Growth 2024–2030",
        market_comparison_title: "HAVENIS AI vs. Camera Systems",
        market_comparison_desc: "Our unique selling proposition is the combination of precision and absolute privacy.",
        market_comparison_vis: "Comparison Graphic: HAVENIS vs. Camera (Privacy, Accuracy, Adoption Rate)",
        market_exit_title_detail: "Strategic Exit to Big Tech",
        market_exit_text_detail: "Our focus on HNWIs and patented, ethical technology makes us the ideal acquisition target for Google, Apple, or Amazon, who urgently need a privacy-compliant solution for their ambient health ecosystems.",
        financials_title: "Funding Need & Growth Plan",
        financials_subtitle: "Seeking €800,000 Seed capital for technology finalization and market entry.",
        financials_plan_title: "Funding Plan (Seed → Series A)",
        financials_t1_date: "Now (Seed)",
        financials_t1_amount: "€ 0.8M",
        financials_t1_use: "Finalize SENSING CORE V1.0, 10+ Pilot Projects (HNWI/Clinics), Build Partner Network.",
        financials_t2_date: "Q3 2026 (Series A)",
        financials_t2_amount: "€ 2.5 - 3M",
        financials_t2_use: "Hardware Miniaturization (Chip-Level), CE Certification (MedTech), Scale Sales DACH.",
        financials_alloc_title: "Investment Allocation (Seed)",
        financials_cta_title: "Join the First 100 Seed Investors",
        financials_cta_desc: "Secure exclusive access and potential IP share rights as an early supporter. Each ticket: €10,000.",
        financials_cta_button: "Become a Seed Investor Now",
        team_detail_title: "Team & Advisory Board",
        team_detail_subtitle: "A core team with a deep-tech focus, complemented by industry experts.",
        team_m1_name_detail: "Danilo Kuss",
        team_m1_role_detail: "CEO & CTO",
        team_m1_desc_detail: "Expert RF-AI & Embedded Systems.",
        team_m2_name_detail: "Sarah Le Roux",
        team_m2_role_detail: "COO & Strategy",
        team_m2_desc_detail: "B2B Sales & Partner Networks.",
        team_m3_name_detail: "Advisory Board",
        team_m3_role_detail: "(Planned)",
        team_m3_desc_detail: "RegTech, MedTech & HNWI Security.",
        team_map_vis: "Diagram: Core Expertise Map (Research / AI / Sensing / Design / Business)",
        contact_form_title: "Contact & Pitch Deck Request",
        contact_form_subtitle: "Request the complete Seed Investment Pitch Deck. After review, we will automatically send you the PDF.",
        contact_name: "Name",
        contact_email: "Email",
        contact_type: "Investor Type",
        contact_select: "Please select...",
        contact_vc: "Venture Capital",
        contact_angel: "Business Angel",
        contact_fo: "Family Office",
        contact_strategic: "Strategic Investor",
        contact_other: "Other",
        contact_message: "Message (Optional)",
        contact_button: "Request Pitch Deck / Investor PDF",
        contact_disclaimer: "Your data will be treated confidentially and used solely for sending the pitch deck and contacting you.",
        footer_copy_detail: "&copy; 2025 HAVENIS AI | Fürstenwalde, Germany | All rights reserved.",
        footer_contact_detail: "info@havenis.ai",
        footer_version_detail: "Version Seed 1.0",
        cta_sending: "Sending request...",
        cta_success: "Success! Pitch deck has been sent to your email.",
        cta_error: "Error sending. Please try again.",
    },,

        // Team Section
        team_title: "Meet Our Team",
        team_subtitle: "Exceptional talent driving the future of ethical AI sensing. Leading experts in RF-AI, embedded systems, and health tech innovation.",
        team_ceo: "CEO & CTO",
        team_danilo_desc: "Visionary leader with deep expertise in RF-AI & Embedded Systems. Spearheading HAVENIS's innovation in contactless vital sensing.",
        team_cofounder: "Co-Founder",
        team_member2_desc: "Expert in healthcare technology and market expansion.",
        team_engineer: "Lead Engineer",
        team_member3_desc: "Specialized in AI signal processing and embedded systems development.",
        team_cta_desc: "Join our growing team of innovators pushing the boundaries of AI sensing technology.",
        team_cta_button: "Join Our Team",
        expertise: "Expertise"
        fr: {
        nav_vision: "Vision", nav_product: "Produit", nav_tech: "Technologie", nav_market: "Marché", nav_contact: "Contact",
        hero_title: "HAVENIS AI – <span class=\"highlight\">La Révolution du Human Sensing</span>",
        hero_subtitle: "Surveillance vitale par IA grâce à des ondes invisibles – sain, privé, précis.",
        hero_cta_primary: "Explorer l'Investissement Seed", hero_cta_secondary: "Découvrir la Technologie",
        vision_title: "Vision & Mission",
        vision_text_1: "Nous révolutionnons la surveillance de la santé et la sécurité grâce à la détection éthique par IA. Notre vision est un monde où la technologie protège sans observer.",
        vision_text_2: "Notre Mission : Développer le premier système de détection non invasif au monde qui respecte la vie privée et fournit des informations préventives sur la santé et la sécurité.",
        vision_promise: "Promesse Marché : « Sécurité invisible – Santé qui remarque tout. »",
        vision_vis: 'Diagramme : "Du Wi-Fi à la Détection Vitale – La Prochaine Interface de la Santé"',
        product_title: "Architecture Produit : SENSING CORE V1.0",
        product_subtitle: "Une plateforme robuste et évolutive pour la perception non invasive.",
        product_schema_title: "Schéma 3D : Flux de Données",
        product_schema_text: "Notre système capture les données CSI Wi-Fi, les traite localement sur la puce Edge AI (SENSING CORE), extrait des métriques anonymisées et les envoie de manière sécurisée au cloud pour analyses et tableaux de bord.",
        product_schema_vis: "Schéma 3D : SENSING CORE V1.0 (Capture → Edge AI → Cloud → Tableau de bord)",
        product_layers_title: "Diagramme des Couches IA",
        product_layers_text: "Notre IA repose sur plusieurs couches : prétraitement du signal, extraction de caractéristiques par apprentissage profond et classification des postures, mouvements et paramètres vitaux.",
        product_layers_vis: "Diagramme des couches IA généré",
        use_cases_title: "Cas d'Usage : Où HAVENIS AI Transforme",
        use_cases_subtitle: "Focus sur les marchés exigeant confidentialité et précision maximales.",
        use_case1_title: "Habitat de Luxe & Sécurité HNWI",
        use_case1_text: "Détection d'intrusion invisible, prévention des chutes dans les résidences privées, surveillance discrète des zones sensibles sans caméras.",
        use_case1_vis: "Vis: Intérieur de luxe avec champ de protection invisible",
        use_case2_title: "Santé & Résidences Seniors",
        use_case2_text: "Surveillance sans contact des signes vitaux (respiration, FC), détection des chutes pour seniors, analyse des habitudes de sommeil, surveillance des patients en clinique.",
        use_case2_vis: "Vis: Tableau de bord médecin / Analyse du sommeil",
        use_case3_title: "Sécurité Domotique",
        use_case3_text: "Détection de présence pour contrôle intelligent lumière/climat, alarme intrusion sans fausses alertes animaux, surveillance conforme RGPD.",
        use_case3_vis: "Vis: Interface Domotique avec affichage de présence",
        market_growth_title: "Marché & Potentiel de Croissance",
        market_growth_subtitle: "Nous ciblons le marché en forte croissance de la détection éthique et de la santé ambiante.",
        market_chart_title: "Croissance Marché HealthTech (Monde + UE)",
        market_chart_desc: "Le marché des solutions de santé numérique croît exponentiellement, tiré par la démographie et la technologie.",
        market_chart_vis: "Graphique : Croissance Marché HealthTech 2024–2030",
        market_comparison_title: "HAVENIS AI vs. Systèmes Caméra",
        market_comparison_desc: "Notre proposition de valeur unique est la combinaison de précision et de confidentialité absolue.",
        market_comparison_vis: "Graphique Comparatif : HAVENIS vs. Caméra (Confidentialité, Précision, Taux d'adoption)",
        market_exit_title_detail: "Sortie Stratégique vers Big Tech",
        market_exit_text_detail: "Notre focus sur les HNWI et notre technologie éthique brevetée font de nous la cible d'acquisition idéale pour Google, Apple ou Amazon, qui ont un besoin urgent d'une solution respectueuse de la vie privée pour leurs écosystèmes de santé ambiante.",
        financials_title: "Besoin de Financement & Plan de Croissance",
        financials_subtitle: "Recherche de 800 000 € en Seed pour finalisation technologique et entrée sur le marché.",
        financials_plan_title: "Plan de Financement (Seed → Série A)",
        financials_t1_date: "Maintenant (Seed)",
        financials_t1_amount: "0,8 M€",
        financials_t1_use: "Finaliser SENSING CORE V1.0, 10+ Pilotes (HNWI/Cliniques), Construire réseau partenaires.",
        financials_t2_date: "T3 2026 (Série A)",
        financials_t2_amount: "2,5 - 3 M€",
        financials_t2_use: "Miniaturisation Hardware (Niveau Puce), Certification CE (MedTech), Échelonner ventes DACH.",
        financials_alloc_title: "Allocation des Investissements (Seed)",
        financials_cta_title: "Rejoignez les 100 Premiers Investisseurs Seed",
        financials_cta_desc: "Accès exclusif et droits potentiels sur la PI pour les premiers soutiens. Ticket : 10 000 €.",
        financials_cta_button: "Devenir Investisseur Seed",
        team_detail_title: "Équipe & Conseil Consultatif",
        team_detail_subtitle: "Une équipe cœur axée deep-tech, complétée par des experts du secteur.",
        team_m1_name_detail: "Danilo Kuss",
        team_m1_role_detail: "PDG & CTO",
        team_m1_desc_detail: "Expert RF-IA & Systèmes Embarqués.",
        team_m2_name_detail: "Sarah Le Roux",
        team_m2_role_detail: "COO & Stratégie",
        team_m2_desc_detail: "Ventes B2B & Réseaux Partenaires.",
        team_m3_name_detail: "Conseil Consultatif",
        team_m3_role_detail: "(Prévu)",
        team_m3_desc_detail: "RegTech, MedTech & Sécurité HNWI.",
        team_map_vis: "Diagramme : Carte d'Expertise Cœur (Recherche / IA / Détection / Design / Business)",
        contact_form_title: "Contact & Demande de Pitchdeck",
        contact_form_subtitle: "Demandez le Pitchdeck d'Investissement Seed complet. Après examen, nous vous enverrons automatiquement le PDF.",
        contact_name: "Nom",
        contact_email: "E-mail",
        contact_type: "Type d'Investisseur",
        contact_select: "Veuillez choisir...",
        contact_vc: "Capital-Risque",
        contact_angel: "Business Angel",
        contact_fo: "Family Office",
        contact_strategic: "Investisseur Stratégique",
        contact_other: "Autre",
        contact_message: "Message (Optionnel)",
        contact_button: "Demander Pitchdeck / PDF Investisseur",
        contact_disclaimer: "Vos données seront traitées confidentiellement et utilisées uniquement pour l'envoi du pitchdeck et la prise de contact.",
        footer_copy_detail: "&copy; 2025 HAVENIS AI | Fürstenwalde, Allemagne | Tous droits réservés.",
        footer_contact_detail: "info@havenis.ai",
        footer_version_detail: "Version Seed 1.0",
        cta_sending: "Envoi en cours...",
        cta_success: "Succès ! Le pitchdeck a été envoyé à votre e-mail.",
        cta_error: "Erreur d'envoi. Veuillez réessayer.",
,

        // Team Section
        team_title: "Unser Team",
        team_subtitle: "Außergewöhnliches Talent, das die Zukunft der ethischen KI-Sensorik gestaltet. Führende Experten in RF-KI, Embedded Systems und Health-Tech-Innovation.",
        team_ceo: "CEO & CTO",
        team_danilo_desc: "Visionärer Führungsrolle mit tiefster Expertise in RF-KI & Embedded Systems. Treiber der HAVENIS-Innovation in kontaktloser Vitalerfassung.",
        team_cofounder: "Co-Founder",
        team_member2_desc: "Experte in Gesundheitstechnologie und Marktexpansion.",
        team_engineer: "Lead Engineer",
        team_member3_desc: "Spezialisiert auf KI-Signalverarbeitung und Embedded-Systems-Entwicklung.",
        team_cta_desc: "Treten Sie unserem wachsenden Team von Innovatoren bei, die die Grenzen der KI-Sensortechnologie verschieben.",
        team_cta_button: "Treten Sie unserem Team bei",
        expertise: "Expertise"    }
};